name: Run Crypto Bot

on:
  workflow_dispatch:

  schedule:
    - cron: '0 8 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install requests

      - name: Run bot
        run: python main.py
