name: Run Crypto Bot

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
      BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
      BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install requests

      - name: Run crypto bot
        run: python main.py

      - name: Run Robur bot
        continue-on-error: true
        run: python robur.py

      - name: Run Trading212 bot
        run: python stocks.py

      
      - name: Save portfolio state
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add portfolio_state.json stocks_state.json || true
          git commit -m "Update portfolio state" || echo "No changes to commit"
          git push
